In [95]:
import pandas as pd

In [96]:
df = pd.read_csv('./owid-energy-data.csv')
df.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

In [97]:
columns_needed = [
    "country",
    "year",
    "population",
    "iso_code",
    "gdp",
    "biofuel_electricity",
    "coal_electricity",
    "electricity_demand",
    "electricity_generation",
    "fossil_electricity",
    "gas_electricity",
    "greenhouse_gas_emissions",
    "hydro_electricity",
    "nuclear_electricity",
    "oil_electricity",
    "renewables_electricity",
    "solar_electricity",
    "wind_electricity",
]

df = df[columns_needed]
df.head()

,country,year,population,iso_code,gdp,biofuel_electricity,coal_electricity,electricity_demand,electricity_generation,fossil_electricity,gas_electricity,greenhouse_gas_emissions,hydro_electricity,nuclear_electricity,oil_electricity,renewables_electricity,solar_electricity,wind_electricity
0,ASEAN (Ember),2000,NaN,NaN,NaN,5.87,76.029999,378.609985,378.609985,305.359985,164.259995,216.759995,50.450001,0.0,65.070000,73.250000,0.0,0.0
1,ASEAN (Ember),2001,NaN,NaN,NaN,6.46,86.260002,404.850006,404.850006,327.660004,190.410004,230.860001,54.330002,0.0,50.990002,77.190002,0.0,0.0
2,ASEAN (Ember),2002,NaN,NaN,NaN,6.62,93.430000,433.190002,433.190002,356.670013,208.919998,248.080002,53.290001,0.0,54.320000,76.519997,0.0,0.0
3,ASEAN (Ember),2003,NaN,NaN,NaN,7.45,102.010002,458.299988,458.299988,381.899994,226.509995,264.450012,53.209999,0.0,53.380001,76.400002,0.0,0.0
4,ASEAN (Ember),2004,NaN,NaN,NaN,8.40,115.010002,496.630005,496.630005,418.670013,244.160004,289.839996,52.990002,0.0,59.500000,77.959999,0.0,0.0

In [98]:
# Find missing values
missing_values = df.isnull().sum()


for column in df.columns:
    print(f"{column}: {missing_values[column]/len(df)*100:.2f}")

country: 0.00
year: 0.00
population: 19.28
iso_code: 26.28
gdp: 49.21
biofuel_electricity: 73.86
coal_electricity: 70.10
electricity_demand: 73.68
electricity_generation: 66.97
fossil_electricity: 70.05
gas_electricity: 70.60
greenhouse_gas_emissions: 75.15
hydro_electricity: 59.36
nuclear_electricity: 56.26
oil_electricity: 70.31
renewables_electricity: 59.28
solar_electricity: 59.20
wind_electricity: 59.51

In [99]:
# 1. Number of years of data per country
years_per_country = df.groupby("country").size()

# 2. Count missing values per country for each variable
missing_counts = (
    df
    .groupby("country")
    .apply(lambda x: x.isna().sum())
)

# 3. Convert counts to percentages (normalized by years available)
missing_pct = missing_counts.div(years_per_country, axis=0) * 100

# 4. Inspect results
missing_pct.tail()

/var/folders/2k/cjs987ps21x954v9rk0h4sh80000gp/T/ipykernel_23847/1531822074.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.isna().sum())

,country,year,population,iso_code,gdp,biofuel_electricity,coal_electricity,electricity_demand,electricity_generation,fossil_electricity,gas_electricity,greenhouse_gas_emissions,hydro_electricity,nuclear_electricity,oil_electricity,renewables_electricity,solar_electricity,wind_electricity
country,,,,,,,,,,,,,,,,,,
World,0.0,0.0,0.0,100.0,85.600000,80.000000,68.000000,80.000000,68.000000,68.000000,68.000000,80.000000,52.000000,52.000000,68.000000,52.000000,52.000000,52.000000
Yemen,0.0,0.0,0.0,0.0,4.444444,46.666667,46.666667,46.666667,46.666667,46.666667,46.666667,46.666667,46.666667,11.111111,46.666667,46.666667,46.666667,46.666667
Yugoslavia,0.0,0.0,25.0,100.0,26.086957,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
Zambia,0.0,0.0,0.0,0.0,41.600000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,76.000000,80.800000,80.800000,80.800000,80.800000
Zimbabwe,0.0,0.0,0.0,0.0,41.600000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,64.800000,80.800000,80.800000,80.800000,80.800000

In [100]:
df = df[df["year"] >= 1985].copy()

print("Dataset restricted to years >= 1985.")
print(f"Year range after filtering: {df['year'].min()} - {df['year'].max()}")

Dataset restricted to years >= 1985.
Year range after filtering: 1985 - 2024

In [101]:
# Columns that must meet the data-quality threshold
critical_cols = [
    "iso_code",
    "population",
    "electricity_generation",
    "electricity_demand"
]

# Kosovo is a real country but has no ISO code — exempt it explicitly
EXEMPT = {"Kosovo"}

# Identify countries that violate the 20% missing-data rule
countries_to_drop = missing_pct[
    (missing_pct[critical_cols] > 80).any(axis=1)
].index

countries_to_drop = [c for c in countries_to_drop if c not in EXEMPT]

# Drop those countries from the main dataframe
df_clean = df[~df["country"].isin(countries_to_drop)].copy()

print(f"Dropped {len(countries_to_drop)} countries due to excessive missing data.")
print(f"Remaining countries: {df_clean['country'].nunique()}")
print(f"(Kosovo retained as explicit exemption despite missing iso_code)")

Dropped 133 countries due to excessive missing data.
Remaining countries: 181
(Kosovo retained as explicit exemption despite missing iso_code)

In [102]:
df_clean

,country,year,population,iso_code,gdp,biofuel_electricity,coal_electricity,electricity_demand,electricity_generation,fossil_electricity,gas_electricity,greenhouse_gas_emissions,hydro_electricity,nuclear_electricity,oil_electricity,renewables_electricity,solar_electricity,wind_electricity
774,American Samoa,1985,39128.0,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
775,American Samoa,1986,40588.0,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
776,American Samoa,1987,42095.0,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
777,American Samoa,1988,43634.0,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
778,American Samoa,1989,45207.0,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22848,Yemen,2020,36134867.0,YEM,6.055929e+10,0.0,0.0,2.94,2.94,2.45,0.41,1.70,0.0,0.0,2.04,0.49,0.49,0.0
22849,Yemen,2021,37140234.0,YEM,5.995369e+10,0.0,0.0,2.92,2.92,2.42,0.63,1.72,0.0,0.0,1.79,0.50,0.50,0.0
22850,Yemen,2022,38222878.0,YEM,6.085300e+10,0.0,0.0,3.03,3.03,2.52,0.54,1.77,0.0,0.0,1.98,0.51,0.51,0.0
22851,Yemen,2023,39390800.0,YEM,NaN,0.0,0.0,3.07,3.07,2.55,0.55,1.80,0.0,0.0,2.00,0.52,0.52,0.0
22852,Yemen,2024,40583173.0,YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [103]:
df_clean.to_csv("df_clean.csv", index=False)

solar and wind need to be handled differently from the other columns.
looking at the raw data, every pre-2000 non-null value for both columns is
already 0.0 - so the NaNs before 2000 aren't really missing, they just mean
the country had no capacity yet. same logic applies to post-2000 leading NaNs
(e.g. Bosnia had no wind farms until 2011, so those early 2000s rows should
also be zero, not interpolated). for 2023/2024 it's just a reporting lag so
we carry the last known value forward.

In [104]:

renewable_cols = ["solar_electricity", "wind_electricity"]

def impute_solar_wind(df, col):
    result = df[col].copy()

    for country, group in df.groupby("country"):
        idx = group.index
        years = group["year"]
        vals = group[col]

        # anything before 2000 is a true zero
        pre2000 = idx[years < 2000]
        result.loc[pre2000] = result.loc[pre2000].fillna(0.0)

        post2000_idx = idx[years >= 2000]
        post2000_vals = vals.loc[post2000_idx]

        # if there's no post-2000 data at all just zero fill and move on
        if post2000_vals.isna().all():
            result.loc[post2000_idx] = 0.0
            continue

        first_valid = post2000_vals.first_valid_index()
        last_valid = post2000_vals.last_valid_index()

        # leading NaNs post-2000 = country hadn't built capacity yet, so zero
        leading = post2000_idx[post2000_idx < first_valid]
        result.loc[leading] = result.loc[leading].fillna(0.0)

        # trailing NaNs = 2023/2024 reporting lag, carry last known value
        trailing = post2000_idx[post2000_idx > last_valid]
        if len(trailing) > 0:
            result.loc[trailing] = result.loc[trailing].fillna(post2000_vals.loc[last_valid])

    return result


for col in renewable_cols:
    before = df_clean[col].isna().sum()
    df_clean[col] = impute_solar_wind(df_clean, col)
    after = df_clean[col].isna().sum()
    print(f"{col}: {before} missing -> {after} missing (filled {before - after})")


# quick checks
print()
for col in renewable_cols:
    print(f"{col} negatives: {(df_clean[col] < 0).sum()}")
    pre2000 = df_clean.loc[df_clean["year"] < 2000, col]
    print(f"{col} pre-2000 remaining NaN: {pre2000.isna().sum()}")

# spot check a few countries that had leading post-2000 NaNs
spot_check = {
    "Bosnia and Herzegovina": ("wind_electricity", 2000, 2010),
    "Malta": ("wind_electricity", 2000, 2011),
    "Martinique": ("solar_electricity", 2000, 2005),
}
print()
for country, (col, y1, y2) in spot_check.items():
    vals = df_clean[
        (df_clean["country"] == country) & df_clean["year"].between(y1, y2)
    ][["year", col]]
    print(f"{country} {col} {y1}-{y2}:")
    print(vals.to_string(index=False), "\n")

# check trailing fill worked
print("Uganda solar 2021-2024:")
print(df_clean[(df_clean["country"] == "Uganda") & (df_clean["year"] >= 2021)][["year", "solar_electricity"]].to_string(index=False))

solar_electricity: 1525 missing -> 0 missing (filled 1525)
wind_electricity: 1597 missing -> 2 missing (filled 1595)

solar_electricity negatives: 0
solar_electricity pre-2000 remaining NaN: 0
wind_electricity negatives: 0
wind_electricity pre-2000 remaining NaN: 0

Bosnia and Herzegovina wind_electricity 2000-2010:
 year  wind_electricity
 2000               0.0
 2001               0.0
 2002               0.0
 2003               0.0
 2004               0.0
 2005               0.0
 2006               0.0
 2007               0.0
 2008               0.0
 2009               0.0
 2010               0.0

Malta wind_electricity 2000-2011:
 year  wind_electricity
 2000               0.0
 2001               0.0
 2002               0.0
 2003               0.0
 2004               0.0
 2005               0.0
 2006               0.0
 2007               0.0
 2008               0.0
 2009               0.0
 2010               0.0
 2011               0.0

Martinique solar_electricity 2000-2005:
 year  solar_electricity
 2000                0.0
 2001                0.0
 2002                0.0
 2003                0.0
 2004                0.0
 2005                0.0

Uganda solar 2021-2024:
 year  solar_electricity
 2021               0.13
 2022               0.15
 2023               0.15

In [105]:
# ── Fossil: fossil_electricity = coal + oil + gas ─────────────────────────────
FOSSIL_COLS = ["coal_electricity", "oil_electricity", "gas_electricity", "fossil_electricity"]

print("Missing BEFORE fossil imputation:")
print(df_clean[FOSSIL_COLS].isnull().sum().to_string())

# Case A: gas missing, coal + oil + fossil present → gas ≈ 0
mask_a = (
    df_clean["coal_electricity"].notna()
    & df_clean["oil_electricity"].notna()
    & df_clean["gas_electricity"].isna()
    & df_clean["fossil_electricity"].notna()
)
df_clean.loc[mask_a, "gas_electricity"] = 0.0
print(f"\nCase A — gas_electricity = 0: {mask_a.sum()} rows")

# Case B: oil missing, coal + gas + fossil present → oil = fossil - coal - gas
mask_b = (
    df_clean["coal_electricity"].notna()
    & df_clean["oil_electricity"].isna()
    & df_clean["gas_electricity"].notna()
    & df_clean["fossil_electricity"].notna()
)
df_clean.loc[mask_b, "oil_electricity"] = (
    df_clean.loc[mask_b, "fossil_electricity"]
    - df_clean.loc[mask_b, "coal_electricity"]
    - df_clean.loc[mask_b, "gas_electricity"]
)
print(f"Case B — oil_electricity = fossil - coal - gas: {mask_b.sum()} rows")

# Case C: coal missing, oil + gas + fossil present → coal = fossil - oil - gas
mask_c = (
    df_clean["coal_electricity"].isna()
    & df_clean["oil_electricity"].notna()
    & df_clean["gas_electricity"].notna()
    & df_clean["fossil_electricity"].notna()
)
df_clean.loc[mask_c, "coal_electricity"] = (
    df_clean.loc[mask_c, "fossil_electricity"]
    - df_clean.loc[mask_c, "oil_electricity"]
    - df_clean.loc[mask_c, "gas_electricity"]
)
print(f"Case C — coal_electricity = fossil - oil - gas: {mask_c.sum()} rows")

# Case D: fossil missing, all 3 components present → fossil = coal + oil + gas
mask_d = (
    df_clean["coal_electricity"].notna()
    & df_clean["oil_electricity"].notna()
    & df_clean["gas_electricity"].notna()
    & df_clean["fossil_electricity"].isna()
)
df_clean.loc[mask_d, "fossil_electricity"] = (
    df_clean.loc[mask_d, "coal_electricity"]
    + df_clean.loc[mask_d, "oil_electricity"]
    + df_clean.loc[mask_d, "gas_electricity"]
)
print(f"Case D — fossil_electricity = coal + oil + gas: {mask_d.sum()} rows")

print("\nMissing AFTER fossil imputation:")
print(df_clean[FOSSIL_COLS].isnull().sum().to_string())

# Verification
check_f = df_clean[FOSSIL_COLS].dropna().copy()
check_f["computed"] = check_f[["coal_electricity", "oil_electricity", "gas_electricity"]].sum(axis=1)
check_f["diff"] = (check_f["computed"] - check_f["fossil_electricity"]).abs()
print(f"\nVerification — rows with all 4 columns: {len(check_f)}")
print(f"  Max |coal+oil+gas - fossil|: {check_f['diff'].max():.4f}")
print(f"  Rows with diff > 0.1:        {(check_f['diff'] > 0.1).sum()}")
print(f"  Negative oil values:         {(df_clean['oil_electricity'] < 0).sum()}")
print(f"  Negative gas values:         {(df_clean['gas_electricity'] < 0).sum()}")
print(f"  Negative coal values:        {(df_clean['coal_electricity'] < 0).sum()}")

Missing BEFORE fossil imputation:
coal_electricity      1978
oil_electricity       1922
gas_electricity       2048
fossil_electricity    1921

Case A — gas_electricity = 0: 69 rows
Case B — oil_electricity = fossil - coal - gas: 0 rows
Case C — coal_electricity = fossil - oil - gas: 0 rows
Case D — fossil_electricity = coal + oil + gas: 0 rows

Missing AFTER fossil imputation:
coal_electricity      1978
oil_electricity       1922
gas_electricity       1979
fossil_electricity    1921

Verification — rows with all 4 columns: 5015
  Max |coal+oil+gas - fossil|: 0.0005
  Rows with diff > 0.1:        0
  Negative oil values:         0
  Negative gas values:         0
  Negative coal values:        0

In [106]:
# ── Renewables: renewables_electricity = solar + hydro + wind + biofuel ───────
RENEW_COMPS = ["solar_electricity", "hydro_electricity", "wind_electricity", "biofuel_electricity"]
RENEW_TOTAL = "renewables_electricity"
THRESHOLD = 0.001  # TWh — prevents incorrect zero-fills on near-zero residuals

print("Missing BEFORE renewables imputation:")
print(df_clean[RENEW_COMPS + [RENEW_TOTAL]].isnull().sum().to_string())

cells_filled = 0

# Case A: exactly 1 component missing, others + renewables present
#         compute residual; fill if ≥ 0 (zero-fill if residual ≈ 0, value if positive)
for col in RENEW_COMPS:
    others = [c for c in RENEW_COMPS if c != col]
    mask = (
        df_clean[col].isna()
        & df_clean[others].notna().all(axis=1)
        & df_clean[RENEW_TOTAL].notna()
    )
    if mask.sum() == 0:
        continue
    residual = df_clean.loc[mask, RENEW_TOTAL] - df_clean.loc[mask, others].sum(axis=1)
    zero_idx = residual[residual.abs() < THRESHOLD].index
    pos_idx  = residual[residual >= THRESHOLD].index
    neg_idx  = residual[residual < -THRESHOLD].index
    df_clean.loc[zero_idx, col] = 0.0
    df_clean.loc[pos_idx,  col] = residual[pos_idx]
    n = len(zero_idx) + len(pos_idx)
    cells_filled += n
    print(f"Case A — {col}: {n} rows filled  ({len(neg_idx)} negative residuals skipped)")

# Case B: renewables total missing, all 4 components present → sum them
mask_total = (
    df_clean[RENEW_TOTAL].isna()
    & df_clean[RENEW_COMPS].notna().all(axis=1)
)
df_clean.loc[mask_total, RENEW_TOTAL] = df_clean.loc[mask_total, RENEW_COMPS].sum(axis=1)
cells_filled += mask_total.sum()
print(f"Case B — renewables_electricity = sum of 4 components: {mask_total.sum()} rows")

print(f"\nTotal cells filled: {cells_filled}")
print("\nMissing AFTER renewables imputation:")
print(df_clean[RENEW_COMPS + [RENEW_TOTAL]].isnull().sum().to_string())

# Verification
check_r = df_clean[RENEW_COMPS + [RENEW_TOTAL]].dropna().copy()
check_r["computed"] = check_r[RENEW_COMPS].sum(axis=1)
check_r["diff"] = (check_r["computed"] - check_r[RENEW_TOTAL]).abs()
print(f"\nVerification — rows with all 5 columns: {len(check_r)}")
print(f"  Max |sum_of_4 - renewables|: {check_r['diff'].max():.4f}")
print(f"  Rows with diff > 0.1:        {(check_r['diff'] > 0.1).sum()}")

Missing BEFORE renewables imputation:
solar_electricity            0
hydro_electricity         1526
wind_electricity             2
biofuel_electricity       2339
renewables_electricity    1507
Case A — hydro_electricity: 4 rows filled  (0 negative residuals skipped)
Case A — wind_electricity: 2 rows filled  (0 negative residuals skipped)
Case A — biofuel_electricity: 817 rows filled  (0 negative residuals skipped)
Case B — renewables_electricity = sum of 4 components: 0 rows

Total cells filled: 823

Missing AFTER renewables imputation:
solar_electricity            0
hydro_electricity         1522
wind_electricity             0
biofuel_electricity       1522
renewables_electricity    1507

Verification — rows with all 5 columns: 5472
  Max |sum_of_4 - renewables|: 19.1600
  Rows with diff > 0.1:        399

In [107]:
# ── Generation: electricity_generation = fossil + renewables + nuclear ─────────
GEN_PARTS = ["fossil_electricity", "renewables_electricity", "nuclear_electricity"]
GEN_TOTAL = "electricity_generation"

print("Missing BEFORE generation imputation:")
print(df_clean[[GEN_TOTAL] + GEN_PARTS].isnull().sum().to_string())

# Case A: generation missing, all 3 parts present → sum them
mask_gen = (
    df_clean[GEN_TOTAL].isna()
    & df_clean[GEN_PARTS].notna().all(axis=1)
)
df_clean.loc[mask_gen, GEN_TOTAL] = df_clean.loc[mask_gen, GEN_PARTS].sum(axis=1)
print(f"\nCase A — electricity_generation = fossil + renewables + nuclear: {mask_gen.sum()} rows")

# Case B: one part missing, others + generation present → solve by residual
for col in GEN_PARTS:
    others = [c for c in GEN_PARTS if c != col]
    mask = (
        df_clean[col].isna()
        & df_clean[others].notna().all(axis=1)
        & df_clean[GEN_TOTAL].notna()
    )
    if mask.sum() == 0:
        continue
    residual = df_clean.loc[mask, GEN_TOTAL] - df_clean.loc[mask, others].sum(axis=1)
    pos_idx = residual[residual >= 0].index
    neg_idx = residual[residual < 0].index
    df_clean.loc[pos_idx, col] = residual[pos_idx]
    print(f"Case B — {col} = generation - others: {len(pos_idx)} rows filled  ({len(neg_idx)} negative skipped)")

print("\nMissing AFTER generation imputation:")
print(df_clean[[GEN_TOTAL] + GEN_PARTS].isnull().sum().to_string())

# Verification
check_g = df_clean[[GEN_TOTAL] + GEN_PARTS].dropna().copy()
check_g["computed"] = check_g[GEN_PARTS].sum(axis=1)
check_g["diff"] = (check_g["computed"] - check_g[GEN_TOTAL]).abs()
print(f"\nVerification — rows with all 4 columns: {len(check_g)}")
print(f"  Max |fossil+renewables+nuclear - generation|: {check_g['diff'].max():.4f}")
print(f"  Rows with diff > 0.1: {(check_g['diff'] > 0.1).sum()}")

Missing BEFORE generation imputation:
electricity_generation    1507
fossil_electricity        1921
renewables_electricity    1507
nuclear_electricity       1456

Case A — electricity_generation = fossil + renewables + nuclear: 0 rows
Case B — fossil_electricity = generation - others: 414 rows filled  (0 negative skipped)
Case B — nuclear_electricity = generation - others: 64 rows filled  (42 negative skipped)

Missing AFTER generation imputation:
electricity_generation    1507
fossil_electricity        1507
renewables_electricity    1507
nuclear_electricity       1392

Verification — rows with all 4 columns: 5445
  Max |fossil+renewables+nuclear - generation|: 18.2941
  Rows with diff > 0.1: 162

In [108]:
# ── Forward-fill trailing NaNs (reporting lag) ────────────────────────────────
# Leading NaNs (country hadn't started reporting) are left as-is.
# Trailing NaNs (2023/2024 reporting lag) are filled with the last known value.
FFILL_COLS = [
    "gdp",
    "electricity_demand",
    "electricity_generation",
    "nuclear_electricity",
    "greenhouse_gas_emissions",
    "coal_electricity",
]

print("Missing BEFORE forward-fill:")
print(df_clean[FFILL_COLS].isnull().sum().to_string())

df_clean = df_clean.sort_values(["country", "year"]).reset_index(drop=True)

for col in FFILL_COLS:
    before = df_clean[col].isna().sum()
    df_clean[col] = df_clean.groupby("country")[col].transform(
        lambda s: s.ffill()
    )
    after = df_clean[col].isna().sum()
    print(f"  {col}: {before - after} trailing cells filled  ({after} remaining leading NaNs)")

print("\nMissing AFTER forward-fill:")
print(df_clean[FFILL_COLS].isnull().sum().to_string())

Missing BEFORE forward-fill:
gdp                         2003
electricity_demand          2298
electricity_generation      1507
nuclear_electricity         1392
greenhouse_gas_emissions    2630
coal_electricity            1978
  gdp: 234 trailing cells filled  (1769 remaining leading NaNs)
  electricity_demand: 62 trailing cells filled  (2236 remaining leading NaNs)
  electricity_generation: 56 trailing cells filled  (1451 remaining leading NaNs)
  nuclear_electricity: 90 trailing cells filled  (1302 remaining leading NaNs)
  greenhouse_gas_emissions: 64 trailing cells filled  (2566 remaining leading NaNs)
  coal_electricity: 58 trailing cells filled  (1920 remaining leading NaNs)

Missing AFTER forward-fill:
gdp                         1769
electricity_demand          2236
electricity_generation      1451
nuclear_electricity         1302
greenhouse_gas_emissions    2566
coal_electricity            1920

In [109]:
# ── Zero-fill leading NaNs for capacity columns ───────────────────────────────
# No data before a country's first reported year = no capacity, not missing reporting.
# Only leading NaNs are zero-filled; trailing and interior NaNs are left as-is.
CAPACITY_COLS = ["coal_electricity", "nuclear_electricity", "hydro_electricity", "biofuel_electricity"]

print("Missing BEFORE capacity zero-fill:")
print(df_clean[CAPACITY_COLS].isnull().sum().to_string())

df_clean = df_clean.sort_values(["country", "year"]).reset_index(drop=True)

for col in CAPACITY_COLS:
    before = df_clean[col].isna().sum()
    def zero_fill_leading(s):
        first_valid = s.first_valid_index()
        if first_valid is None:
            return s.fillna(0.0)          # all NaN — country never reported, safe to zero
        s = s.copy()
        s.loc[:first_valid].fillna(0.0, inplace=True)
        return s
    df_clean[col] = df_clean.groupby("country")[col].transform(zero_fill_leading)
    after = df_clean[col].isna().sum()
    print(f"  {col}: {before - after} leading cells zero-filled  ({after} remaining)")

print("\nMissing AFTER capacity zero-fill:")
print(df_clean[CAPACITY_COLS].isnull().sum().to_string())

Missing BEFORE capacity zero-fill:
coal_electricity       1920
nuclear_electricity    1302
hydro_electricity      1522
biofuel_electricity    1522
  coal_electricity: 1920 leading cells zero-filled  (0 remaining)
  nuclear_electricity: 1302 leading cells zero-filled  (0 remaining)
  hydro_electricity: 1466 leading cells zero-filled  (56 remaining)
  biofuel_electricity: 1466 leading cells zero-filled  (56 remaining)

Missing AFTER capacity zero-fill:
coal_electricity        0
nuclear_electricity     0
hydro_electricity      56
biofuel_electricity    56

/var/folders/2k/cjs987ps21x954v9rk0h4sh80000gp/T/ipykernel_23847/3173188783.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.loc[:first_valid].fillna(0.0, inplace=True)
/var/folders/2k/cjs987ps21x954v9rk0h4sh80000gp/T/ipykernel_23847/3173188783.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.loc[:first_valid].fillna(0.0, inplace=True)
/var/folders/2k/cjs987ps21x954v9rk0h4sh80000gp/T/ipykernel_23847/3173188783.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.loc[:first_valid].fillna(0.0, inplace=True)
/var/folders/2k/cjs987ps21x954v9rk0h4sh80000gp/T/ipykernel_23847/3173188783.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.loc[:first_valid].fillna(0.0, inplace=True)

In [110]:
# ── Backward trend extrapolation for leading NaNs (1985–reporting start) ──────
# For each country, fit a linear trend on the first available data points
# and extrapolate backward to fill years before reporting began.
import numpy as np

BACKCAST_COLS = [
    "gdp",
    "electricity_demand",
    "electricity_generation",
    "fossil_electricity",
    "renewables_electricity",
    "greenhouse_gas_emissions",
]

print("Missing BEFORE backward extrapolation:")
print(df_clean[BACKCAST_COLS].isnull().sum().to_string())

df_clean = df_clean.sort_values(["country", "year"]).reset_index(drop=True)

for col in BACKCAST_COLS:
    before = df_clean[col].isna().sum()

    def backcast(s, _col=col):
        if s.notna().sum() == 0:
            return s  # no data at all — leave as NaN

        first_valid_pos = s.first_valid_index()
        leading_idx = s.loc[:first_valid_pos].index[:-1]  # NaN indices before first valid

        if len(leading_idx) == 0:
            return s  # no leading NaNs for this country

        valid = s.dropna()

        if len(valid) < 2:
            # Not enough points for a trend — back-fill with constant
            s = s.copy()
            s.loc[leading_idx] = valid.iloc[0]
            return s

        # Fit linear trend on first 5 available data points
        anchor = valid.iloc[:5]
        years = df_clean.loc[anchor.index, "year"].values.astype(float)
        values = anchor.values.astype(float)
        slope, intercept = np.polyfit(years, values, 1)

        s = s.copy()
        for i in leading_idx:
            year = df_clean.loc[i, "year"]
            s.loc[i] = max(slope * year + intercept, 0.0)  # clamp at 0

        return s

    df_clean[col] = df_clean.groupby("country")[col].transform(backcast)
    after = df_clean[col].isna().sum()
    print(f"  {col}: {before - after} cells back-extrapolated  ({after} remaining)")

print("\nMissing AFTER backward extrapolation:")
print(df_clean[BACKCAST_COLS].isnull().sum().to_string())

Missing BEFORE backward extrapolation:
gdp                         1769
electricity_demand          2236
electricity_generation      1451
fossil_electricity          1507
renewables_electricity      1507
greenhouse_gas_emissions    2566
  gdp: 0 cells back-extrapolated  (1769 remaining)
  electricity_demand: 2236 cells back-extrapolated  (0 remaining)
  electricity_generation: 1451 cells back-extrapolated  (0 remaining)
  fossil_electricity: 1451 cells back-extrapolated  (56 remaining)
  renewables_electricity: 1451 cells back-extrapolated  (56 remaining)
  greenhouse_gas_emissions: 2566 cells back-extrapolated  (0 remaining)

Missing AFTER backward extrapolation:
gdp                         1769
electricity_demand             0
electricity_generation         0
fossil_electricity            56
renewables_electricity        56
greenhouse_gas_emissions       0

In [111]:
# ── GDP imputation via regional median GDP per capita ─────────────────────────
# Countries with no World Bank GDP data are imputed using the median GDP per
# capita of their region in each year, scaled by their own population.

REGION_MAP = {
    # Latin America & Caribbean
    "Antigua and Barbuda":               "Latin America & Caribbean",
    "Argentina":                         "Latin America & Caribbean",
    "Aruba":                             "Latin America & Caribbean",
    "Bahamas":                           "Latin America & Caribbean",
    "Belize":                            "Latin America & Caribbean",
    "Bermuda":                           "Latin America & Caribbean",
    "Bolivia":                           "Latin America & Caribbean",
    "Brazil":                            "Latin America & Caribbean",
    "British Virgin Islands":            "Latin America & Caribbean",
    "Cayman Islands":                    "Latin America & Caribbean",
    "Chile":                             "Latin America & Caribbean",
    "Colombia":                          "Latin America & Caribbean",
    "Costa Rica":                        "Latin America & Caribbean",
    "Dominica":                          "Latin America & Caribbean",
    "Dominican Republic":                "Latin America & Caribbean",
    "Ecuador":                           "Latin America & Caribbean",
    "El Salvador":                       "Latin America & Caribbean",
    "French Guiana":                     "Latin America & Caribbean",
    "Grenada":                           "Latin America & Caribbean",
    "Guadeloupe":                        "Latin America & Caribbean",
    "Guyana":                            "Latin America & Caribbean",
    "Haiti":                             "Latin America & Caribbean",
    "Honduras":                          "Latin America & Caribbean",
    "Jamaica":                           "Latin America & Caribbean",
    "Martinique":                        "Latin America & Caribbean",
    "Mexico":                            "Latin America & Caribbean",
    "Montserrat":                        "Latin America & Caribbean",
    "Nicaragua":                         "Latin America & Caribbean",
    "Panama":                            "Latin America & Caribbean",
    "Paraguay":                          "Latin America & Caribbean",
    "Peru":                              "Latin America & Caribbean",
    "Puerto Rico":                       "Latin America & Caribbean",
    "Saint Kitts and Nevis":             "Latin America & Caribbean",
    "Saint Lucia":                       "Latin America & Caribbean",
    "Saint Pierre and Miquelon":         "Latin America & Caribbean",
    "Saint Vincent and the Grenadines":  "Latin America & Caribbean",
    "Turks and Caicos Islands":          "Latin America & Caribbean",
    "United States Virgin Islands":      "Latin America & Caribbean",
    "Uruguay":                           "Latin America & Caribbean",
    # Sub-Saharan Africa
    "Benin":                             "Sub-Saharan Africa",
    "Burkina Faso":                      "Sub-Saharan Africa",
    "Cape Verde":                        "Sub-Saharan Africa",
    "Central African Republic":          "Sub-Saharan Africa",
    "Chad":                              "Sub-Saharan Africa",
    "Comoros":                           "Sub-Saharan Africa",
    "Djibouti":                          "Sub-Saharan Africa",
    "Equatorial Guinea":                 "Sub-Saharan Africa",
    "Eritrea":                           "Sub-Saharan Africa",
    "Ethiopia":                          "Sub-Saharan Africa",
    "Gambia":                            "Sub-Saharan Africa",
    "Guinea":                            "Sub-Saharan Africa",
    "Guinea-Bissau":                     "Sub-Saharan Africa",
    "Kenya":                             "Sub-Saharan Africa",
    "Lesotho":                           "Sub-Saharan Africa",
    "Liberia":                           "Sub-Saharan Africa",
    "Malawi":                            "Sub-Saharan Africa",
    "Mali":                              "Sub-Saharan Africa",
    "Mauritania":                        "Sub-Saharan Africa",
    "Mauritius":                         "Sub-Saharan Africa",
    "Namibia":                           "Sub-Saharan Africa",
    "Nigeria":                           "Sub-Saharan Africa",
    "Reunion":                           "Sub-Saharan Africa",
    "Rwanda":                            "Sub-Saharan Africa",
    "Saint Helena":                      "Sub-Saharan Africa",
    "Sao Tome and Principe":             "Sub-Saharan Africa",
    "Senegal":                           "Sub-Saharan Africa",
    "Seychelles":                        "Sub-Saharan Africa",
    "Sierra Leone":                      "Sub-Saharan Africa",
    "Somalia":                           "Sub-Saharan Africa",
    "South Africa":                      "Sub-Saharan Africa",
    "South Sudan":                       "Sub-Saharan Africa",
    "Togo":                              "Sub-Saharan Africa",
    "Uganda":                            "Sub-Saharan Africa",
    # Middle East & North Africa
    "Egypt":                             "Middle East & North Africa",
    "Iran":                              "Middle East & North Africa",
    "Jordan":                            "Middle East & North Africa",
    "Kuwait":                            "Middle East & North Africa",
    "Lebanon":                           "Middle East & North Africa",
    "Morocco":                           "Middle East & North Africa",
    "Oman":                              "Middle East & North Africa",
    "Palestine":                         "Middle East & North Africa",
    "Qatar":                             "Middle East & North Africa",
    "Saudi Arabia":                      "Middle East & North Africa",
    "Sudan":                             "Middle East & North Africa",
    "Tunisia":                           "Middle East & North Africa",
    "United Arab Emirates":              "Middle East & North Africa",
    "Western Sahara":                    "Middle East & North Africa",
    "Yemen":                             "Middle East & North Africa",
    # South & Southeast Asia
    "Bangladesh":                        "South & Southeast Asia",
    "Bhutan":                            "South & Southeast Asia",
    "Cambodia":                          "South & Southeast Asia",
    "East Timor":                        "South & Southeast Asia",
    "India":                             "South & Southeast Asia",
    "Indonesia":                         "South & Southeast Asia",
    "Laos":                              "South & Southeast Asia",
    "Malaysia":                          "South & Southeast Asia",
    "Maldives":                          "South & Southeast Asia",
    "Myanmar":                           "South & Southeast Asia",
    "Pakistan":                          "South & Southeast Asia",
    "Philippines":                       "South & Southeast Asia",
    "Singapore":                         "South & Southeast Asia",
    "Sri Lanka":                         "South & Southeast Asia",
    "Thailand":                          "South & Southeast Asia",
    "Vietnam":                           "South & Southeast Asia",
    # East Asia & Pacific
    "American Samoa":                    "East Asia & Pacific",
    "Australia":                         "East Asia & Pacific",
    "China":                             "East Asia & Pacific",
    "Cook Islands":                      "East Asia & Pacific",
    "Fiji":                              "East Asia & Pacific",
    "French Polynesia":                  "East Asia & Pacific",
    "Guam":                              "East Asia & Pacific",
    "Hong Kong":                         "East Asia & Pacific",
    "Japan":                             "East Asia & Pacific",
    "Kiribati":                          "East Asia & Pacific",
    "Macao":                             "East Asia & Pacific",
    "Mongolia":                          "East Asia & Pacific",
    "Nauru":                             "East Asia & Pacific",
    "New Caledonia":                     "East Asia & Pacific",
    "New Zealand":                       "East Asia & Pacific",
    "Niue":                              "East Asia & Pacific",
    "Papua New Guinea":                  "East Asia & Pacific",
    "Samoa":                             "East Asia & Pacific",
    "Solomon Islands":                   "East Asia & Pacific",
    "South Korea":                       "East Asia & Pacific",
    "Taiwan":                            "East Asia & Pacific",
    "Tonga":                             "East Asia & Pacific",
    "Vanuatu":                           "East Asia & Pacific",
    # Eastern Europe & Central Asia
    "Armenia":                           "Eastern Europe & Central Asia",
    "Azerbaijan":                        "Eastern Europe & Central Asia",
    "Belarus":                           "Eastern Europe & Central Asia",
    "Bosnia and Herzegovina":            "Eastern Europe & Central Asia",
    "Bulgaria":                          "Eastern Europe & Central Asia",
    "Croatia":                           "Eastern Europe & Central Asia",
    "Czechia":                           "Eastern Europe & Central Asia",
    "Estonia":                           "Eastern Europe & Central Asia",
    "Georgia":                           "Eastern Europe & Central Asia",
    "Kazakhstan":                        "Eastern Europe & Central Asia",
    "Kosovo":                            "Eastern Europe & Central Asia",
    "Kyrgyzstan":                        "Eastern Europe & Central Asia",
    "Latvia":                            "Eastern Europe & Central Asia",
    "Lithuania":                         "Eastern Europe & Central Asia",
    "Moldova":                           "Eastern Europe & Central Asia",
    "Montenegro":                        "Eastern Europe & Central Asia",
    "North Macedonia":                   "Eastern Europe & Central Asia",
    "Poland":                            "Eastern Europe & Central Asia",
    "Romania":                           "Eastern Europe & Central Asia",
    "Russia":                            "Eastern Europe & Central Asia",
    "Serbia":                            "Eastern Europe & Central Asia",
    "Slovakia":                          "Eastern Europe & Central Asia",
    "Slovenia":                          "Eastern Europe & Central Asia",
    "Tajikistan":                        "Eastern Europe & Central Asia",
    "Turkey":                            "Eastern Europe & Central Asia",
    "Turkmenistan":                      "Eastern Europe & Central Asia",
    "Ukraine":                           "Eastern Europe & Central Asia",
    "Uzbekistan":                        "Eastern Europe & Central Asia",
    # Western Europe & North America
    "Austria":                           "Western Europe & North America",
    "Belgium":                           "Western Europe & North America",
    "Canada":                            "Western Europe & North America",
    "Cyprus":                            "Western Europe & North America",
    "Denmark":                           "Western Europe & North America",
    "Falkland Islands":                  "Western Europe & North America",
    "Faroe Islands":                     "Western Europe & North America",
    "Finland":                           "Western Europe & North America",
    "France":                            "Western Europe & North America",
    "Germany":                           "Western Europe & North America",
    "Gibraltar":                         "Western Europe & North America",
    "Greece":                            "Western Europe & North America",
    "Hungary":                           "Western Europe & North America",
    "Iceland":                           "Western Europe & North America",
    "Ireland":                           "Western Europe & North America",
    "Italy":                             "Western Europe & North America",
    "Luxembourg":                        "Western Europe & North America",
    "Malta":                             "Western Europe & North America",
    "Netherlands":                       "Western Europe & North America",
    "Norway":                            "Western Europe & North America",
    "Portugal":                          "Western Europe & North America",
    "Spain":                             "Western Europe & North America",
    "Sweden":                            "Western Europe & North America",
    "Switzerland":                       "Western Europe & North America",
    "United Kingdom":                    "Western Europe & North America",
    "United States":                     "Western Europe & North America",
}

print(f"Missing BEFORE regional GDP imputation: {df_clean['gdp'].isna().sum()}")

# Step 1: assign region to every row
df_clean["_region"] = df_clean["country"].map(REGION_MAP)

# Step 2: GDP per capita for countries that have both GDP and population
df_clean["_gdp_pc"] = df_clean["gdp"] / df_clean["population"]

# Step 3: median GDP per capita per (region, year) from countries WITH data
regional_median = (
    df_clean[df_clean["gdp"].notna() & df_clean["_region"].notna()]
    .groupby(["_region", "year"])["_gdp_pc"]
    .median()
    .reset_index()
    .rename(columns={"_gdp_pc": "_regional_median_gdp_pc"})
)

# Step 4: merge and impute
df_clean = df_clean.merge(regional_median, on=["_region", "year"], how="left")

mask = (
    df_clean["gdp"].isna()
    & df_clean["_regional_median_gdp_pc"].notna()
    & df_clean["population"].notna()
)
df_clean.loc[mask, "gdp"] = (
    df_clean.loc[mask, "_regional_median_gdp_pc"] * df_clean.loc[mask, "population"]
)

filled = mask.sum()
remaining = df_clean["gdp"].isna().sum()
print(f"  Filled {filled} GDP cells using regional median GDP per capita")
print(f"Missing AFTER regional GDP imputation: {remaining}")

# Per-region summary
print("\n── Fill summary by region ──")
for region in sorted(set(REGION_MAP.values())):
    countries = [c for c, r in REGION_MAP.items() if r == region]
    n_missing = df_clean[df_clean["country"].isin(countries)]["gdp"].isna().sum()
    print(f"  {region:<35} remaining NaN: {n_missing}")

# Drop helper columns
df_clean.drop(columns=["_region", "_gdp_pc", "_regional_median_gdp_pc"], inplace=True)

Missing BEFORE regional GDP imputation: 1769
  Filled 1769 GDP cells using regional median GDP per capita
Missing AFTER regional GDP imputation: 0

── Fill summary by region ──
  East Asia & Pacific                 remaining NaN: 0
  Eastern Europe & Central Asia       remaining NaN: 0
  Latin America & Caribbean           remaining NaN: 0
  Middle East & North Africa          remaining NaN: 0
  South & Southeast Asia              remaining NaN: 0
  Sub-Saharan Africa                  remaining NaN: 0
  Western Europe & North America      remaining NaN: 0

In [112]:
# ── Forward-fill remaining interior/trailing NaNs for hydro and biofuel ───────
print("Missing BEFORE hydro/biofuel forward-fill:")
for col in ["hydro_electricity", "biofuel_electricity"]:
    print(f"  {col}: {df_clean[col].isna().sum()}")

for col in ["hydro_electricity", "biofuel_electricity"]:
    before = df_clean[col].isna().sum()
    df_clean[col] = df_clean.groupby("country")[col].transform(lambda s: s.ffill())
    after = df_clean[col].isna().sum()
    print(f"  {col}: {before - after} cells forward-filled  ({after} remaining)")

print("\nMissing AFTER hydro/biofuel forward-fill:")
for col in ["hydro_electricity", "biofuel_electricity"]:
    print(f"  {col}: {df_clean[col].isna().sum()}")

Missing BEFORE hydro/biofuel forward-fill:
  hydro_electricity: 56
  biofuel_electricity: 56
  hydro_electricity: 56 cells forward-filled  (0 remaining)
  biofuel_electricity: 56 cells forward-filled  (0 remaining)

Missing AFTER hydro/biofuel forward-fill:
  hydro_electricity: 0
  biofuel_electricity: 0

In [113]:
# ── Export fully preprocessed dataset ─────────────────────────────────────────
df_clean.to_csv("df_clean.csv", index=False)
print(f"Exported df_clean.csv")
print(f"  Rows:      {len(df_clean)}")
print(f"  Countries: {df_clean['country'].nunique()}")
print(f"  Columns:   {list(df_clean.columns)}")
print(f"\nRemaining missing values:")
print(df_clean.isnull().sum()[df_clean.isnull().sum() > 0].to_string())

Exported df_clean.csv
  Rows:      6994
  Countries: 181
  Columns:   ['country', 'year', 'population', 'iso_code', 'gdp', 'biofuel_electricity', 'coal_electricity', 'electricity_demand', 'electricity_generation', 'fossil_electricity', 'gas_electricity', 'greenhouse_gas_emissions', 'hydro_electricity', 'nuclear_electricity', 'oil_electricity', 'renewables_electricity', 'solar_electricity', 'wind_electricity']

Remaining missing values:
iso_code                    25
fossil_electricity          56
gas_electricity           1979
oil_electricity           1922
renewables_electricity      56