In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('./owid-energy-data.csv')
df.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

In [16]:
columns_needed = [
    "country",
    "year",
    "population",
    "iso_code",
    "gdp",
    "biofuel_electricity",
    "coal_electricity",
    "electricity_demand",
    "electricity_generation",
    "fossil_electricity",
    "gas_electricity",
    "greenhouse_gas_emissions",
    "hydro_electricity",
    "nuclear_electricity",
    "oil_electricity",
    "renewables_electricity",
    "solar_electricity",
    "wind_electricity",
]

df = df[columns_needed]
df.head()

,country,year,population,iso_code,gdp,biofuel_electricity,coal_electricity,electricity_demand,electricity_generation,fossil_electricity,gas_electricity,greenhouse_gas_emissions,hydro_electricity,nuclear_electricity,oil_electricity,renewables_electricity,solar_electricity,wind_electricity
0,ASEAN (Ember),2000,NaN,NaN,NaN,5.87,76.029999,378.609985,378.609985,305.359985,164.259995,216.759995,50.450001,0.0,65.070000,73.250000,0.0,0.0
1,ASEAN (Ember),2001,NaN,NaN,NaN,6.46,86.260002,404.850006,404.850006,327.660004,190.410004,230.860001,54.330002,0.0,50.990002,77.190002,0.0,0.0
2,ASEAN (Ember),2002,NaN,NaN,NaN,6.62,93.430000,433.190002,433.190002,356.670013,208.919998,248.080002,53.290001,0.0,54.320000,76.519997,0.0,0.0
3,ASEAN (Ember),2003,NaN,NaN,NaN,7.45,102.010002,458.299988,458.299988,381.899994,226.509995,264.450012,53.209999,0.0,53.380001,76.400002,0.0,0.0
4,ASEAN (Ember),2004,NaN,NaN,NaN,8.40,115.010002,496.630005,496.630005,418.670013,244.160004,289.839996,52.990002,0.0,59.500000,77.959999,0.0,0.0

In [17]:
# Find missing values
missing_values = df.isnull().sum()


for column in df.columns:
    print(f"{column}: {missing_values[column]/len(df)*100:.2f}")

country: 0.00
year: 0.00
population: 19.28
iso_code: 26.28
gdp: 49.21
biofuel_electricity: 73.86
coal_electricity: 70.10
electricity_demand: 73.68
electricity_generation: 66.97
fossil_electricity: 70.05
gas_electricity: 70.60
greenhouse_gas_emissions: 75.15
hydro_electricity: 59.36
nuclear_electricity: 56.26
oil_electricity: 70.31
renewables_electricity: 59.28
solar_electricity: 59.20
wind_electricity: 59.51

In [18]:
# 1. Number of years of data per country
years_per_country = df.groupby("country").size()

# 2. Count missing values per country for each variable
missing_counts = (
    df
    .groupby("country")
    .apply(lambda x: x.isna().sum())
)

# 3. Convert counts to percentages (normalized by years available)
missing_pct = missing_counts.div(years_per_country, axis=0) * 100

# 4. Inspect results
missing_pct.tail()

,year,population,iso_code,gdp,biofuel_electricity,coal_electricity,electricity_demand,electricity_generation,fossil_electricity,gas_electricity,greenhouse_gas_emissions,hydro_electricity,nuclear_electricity,oil_electricity,renewables_electricity,solar_electricity,wind_electricity
country,,,,,,,,,,,,,,,,,
World,0.0,0.0,100.0,85.600000,80.000000,68.000000,80.000000,68.000000,68.000000,68.000000,80.000000,52.000000,52.000000,68.000000,52.000000,52.000000,52.000000
Yemen,0.0,0.0,0.0,4.444444,46.666667,46.666667,46.666667,46.666667,46.666667,46.666667,46.666667,46.666667,11.111111,46.666667,46.666667,46.666667,46.666667
Yugoslavia,0.0,25.0,100.0,26.086957,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
Zambia,0.0,0.0,0.0,41.600000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,76.000000,80.800000,80.800000,80.800000,80.800000
Zimbabwe,0.0,0.0,0.0,41.600000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,80.800000,64.800000,80.800000,80.800000,80.800000,80.800000

In [19]:
df = df[df["year"] >= 1985].copy()

print("Dataset restricted to years >= 1985.")
print(f"Year range after filtering: {df['year'].min()} - {df['year'].max()}")

Dataset restricted to years >= 1985.
Year range after filtering: 1985 - 2024

In [20]:
# Columns that must meet the data-quality threshold
critical_cols = [
    "iso_code",
    "population",
    "electricity_generation",
    "electricity_demand"
]

# Identify countries that violate the 20% missing-data rule
countries_to_drop = missing_pct[
    (missing_pct[critical_cols] > 50).any(axis=1)
].index

# Drop those countries from the main dataframe
df_clean = df[~df["country"].isin(countries_to_drop)].copy()

print(f"Dropped {len(countries_to_drop)} countries due to excessive missing data.")
print(f"Remaining countries: {df_clean['country'].nunique()}")

Dropped 201 countries due to excessive missing data.
Remaining countries: 113

In [21]:
df_clean

,country,year,population,iso_code,gdp,biofuel_electricity,coal_electricity,electricity_demand,electricity_generation,fossil_electricity,gas_electricity,greenhouse_gas_emissions,hydro_electricity,nuclear_electricity,oil_electricity,renewables_electricity,solar_electricity,wind_electricity
774,American Samoa,1985,39128.0,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
775,American Samoa,1986,40588.0,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
776,American Samoa,1987,42095.0,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
777,American Samoa,1988,43634.0,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
778,American Samoa,1989,45207.0,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22848,Yemen,2020,36134867.0,YEM,6.055929e+10,0.0,0.0,2.94,2.94,2.45,0.41,1.70,0.0,0.0,2.04,0.49,0.49,0.0
22849,Yemen,2021,37140234.0,YEM,5.995369e+10,0.0,0.0,2.92,2.92,2.42,0.63,1.72,0.0,0.0,1.79,0.50,0.50,0.0
22850,Yemen,2022,38222878.0,YEM,6.085300e+10,0.0,0.0,3.03,3.03,2.52,0.54,1.77,0.0,0.0,1.98,0.51,0.51,0.0
22851,Yemen,2023,39390800.0,YEM,NaN,0.0,0.0,3.07,3.07,2.55,0.55,1.80,0.0,0.0,2.00,0.52,0.52,0.0
22852,Yemen,2024,40583173.0,YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [22]:
df_clean.to_csv("df_clean.csv", index=False)

solar and wind need to be handled differently from the other columns.
looking at the raw data, every pre-2000 non-null value for both columns is
already 0.0 - so the NaNs before 2000 aren't really missing, they just mean
the country had no capacity yet. same logic applies to post-2000 leading NaNs
(e.g. Bosnia had no wind farms until 2011, so those early 2000s rows should
also be zero, not interpolated). for 2023/2024 it's just a reporting lag so
we carry the last known value forward.

In [24]:

renewable_cols = ["solar_electricity", "wind_electricity"]

def impute_solar_wind(df, col):
    result = df[col].copy()

    for country, group in df.groupby("country"):
        idx = group.index
        years = group["year"]
        vals = group[col]

        # anything before 2000 is a true zero
        pre2000 = idx[years < 2000]
        result.loc[pre2000] = result.loc[pre2000].fillna(0.0)

        post2000_idx = idx[years >= 2000]
        post2000_vals = vals.loc[post2000_idx]

        # if there's no post-2000 data at all just zero fill and move on
        if post2000_vals.isna().all():
            result.loc[post2000_idx] = 0.0
            continue

        first_valid = post2000_vals.first_valid_index()
        last_valid = post2000_vals.last_valid_index()

        # leading NaNs post-2000 = country hadn't built capacity yet, so zero
        leading = post2000_idx[post2000_idx < first_valid]
        result.loc[leading] = result.loc[leading].fillna(0.0)

        # trailing NaNs = 2023/2024 reporting lag, carry last known value
        trailing = post2000_idx[post2000_idx > last_valid]
        if len(trailing) > 0:
            result.loc[trailing] = result.loc[trailing].fillna(post2000_vals.loc[last_valid])

    return result


for col in renewable_cols:
    before = df_clean[col].isna().sum()
    df_clean[col] = impute_solar_wind(df_clean, col)
    after = df_clean[col].isna().sum()
    print(f"{col}: {before} missing -> {after} missing (filled {before - after})")


# quick checks
print()
for col in renewable_cols:
    print(f"{col} negatives: {(df_clean[col] < 0).sum()}")
    pre2000 = df_clean.loc[df_clean["year"] < 2000, col]
    print(f"{col} pre-2000 remaining NaN: {pre2000.isna().sum()}")

# spot check a few countries that had leading post-2000 NaNs
spot_check = {
    "Bosnia and Herzegovina": ("wind_electricity", 2000, 2010),
    "Malta": ("wind_electricity", 2000, 2011),
    "Martinique": ("solar_electricity", 2000, 2005),
}
print()
for country, (col, y1, y2) in spot_check.items():
    vals = df_clean[
        (df_clean["country"] == country) & df_clean["year"].between(y1, y2)
    ][["year", col]]
    print(f"{country} {col} {y1}-{y2}:")
    print(vals.to_string(index=False), "\n")

# check trailing fill worked
print("Uganda solar 2021-2024:")
print(df_clean[(df_clean["country"] == "Uganda") & (df_clean["year"] >= 2021)][["year", "solar_electricity"]].to_string(index=False))

solar_electricity: 0 missing -> 0 missing (filled 0)
wind_electricity: 0 missing -> 0 missing (filled 0)

solar_electricity negatives: 0
solar_electricity pre-2000 remaining NaN: 0
wind_electricity negatives: 0
wind_electricity pre-2000 remaining NaN: 0

Bosnia and Herzegovina wind_electricity 2000-2010:
 year  wind_electricity
 2000               0.0
 2001               0.0
 2002               0.0
 2003               0.0
 2004               0.0
 2005               0.0
 2006               0.0
 2007               0.0
 2008               0.0
 2009               0.0
 2010               0.0

Malta wind_electricity 2000-2011:
 year  wind_electricity
 2000               0.0
 2001               0.0
 2002               0.0
 2003               0.0
 2004               0.0
 2005               0.0
 2006               0.0
 2007               0.0
 2008               0.0
 2009               0.0
 2010               0.0
 2011               0.0

Martinique solar_electricity 2000-2005:
 year  solar_electricity
 2000                0.0
 2001                0.0
 2002                0.0
 2003                0.0
 2004                0.0
 2005                0.0

Uganda solar 2021-2024:
 year  solar_electricity
 2021               0.13
 2022               0.15
 2023               0.15